stages:
  - build
  - dockerize

# Compile the software and make a tarball
build-software:
  stage: build
  image: ubuntu:20.04
  timeout: 6 hours
  script:
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential tar docker.io
    - pwd
    - ls
    - sh ./install_deps_ubuntu.sh
    - cp config-salas.mk config.mk
    - make echo-targets
    - make install
    - make blob
    - cat ~/.docker/config.json
  artifacts:
    paths:
      - fosshdl.tar.gz

# We should make the docker image in a separate stage
dockerimages:
  stage: dockerize
  image: ubuntu:20.04
  timeout: 1 hour
  dependencies:
    - build-software
  script:
    - cat ~/.docker/config.json
    - make dockerimage
    - docker push registry.gitlab.com/hgpub/fosshdl-dist/fosshdl
