stages:
  - build

# Compile the software and make a tarball
build-software:
  stage: build
  image: ubuntu:20.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential tar
    - pwd
    - ls
    - sh ./install_deps_ubuntu.sh
    - cp config-salas.mk config.mk
    - make echo-targets
    - make install
    - cd /home/salas && tar zcvf fosshdl-`date +%Y%m%d`.tar.gz fosshdl
  artifacts:
    paths:
      - /home/salas/fosshdl*.tar.gz
