stages:
  - build
  - dockerize

# Compile the software and make a tarball
build-software:
  stage: build
  image: ubuntu:22.04
  timeout: 6 hours
  script:
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential tar
    - pwd
    - ls
    - sh ./install_deps_ubuntu.sh
    - cp config-salas.mk config.mk
    - make echo-targets
    - make install
    - make blob
  artifacts:
    paths:
      - fosshdl.tar.gz

# Make the docker image in a separate stage
# Since it's in a separate stage we can't use the "make dockerfile" target
# because that would rebuild everything (because of dependencies in the
# Makefile), so we will just invoke docker. We also want to tag specifically
# the image so it can be pushed to gitlab's container registry
dockerimages:
  stage: dockerize
  image: docker:20.10.7
  timeout: 1 hour
  dependencies:
    - build-software
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
         tag=""
         echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
       else
         tag=":$CI_COMMIT_REF_SLUG"
         echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
       fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - |
      docker login \
        -u "$CI_REGISTRY_USER" \
        -p "$CI_REGISTRY_PASSWORD" \
        $CI_REGISTRY

    - docker push "$CI_REGISTRY_IMAGE${tag}"
